"""empty message

Revision ID: 45a6f485ff80
Revises: cd7ebae3fcdc
Create Date: 2018-08-11 23:44:19.157768

"""

# revision identifiers, used by Alembic.
revision = '45a6f485ff80'
down_revision = 'cd7ebae3fcdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('checkoutid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('bookid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('checkoutid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associations')
    # ### end Alembic commands ###
