"""empty message

Revision ID: bd994d86fee5
Revises: 38f7baedd7df
Create Date: 2018-08-09 23:25:11.580981

"""

# revision identifiers, used by Alembic.
revision = 'bd994d86fee5'
down_revision = '38f7baedd7df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'associations', 'users', ['userid'], ['userid'])
    op.create_foreign_key(None, 'associations', 'books', ['bookid'], ['bookid'])
    op.alter_column("books","publishedDate",existing_type=sa.DATE, type_=sa.DateTime)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'associations', type_='foreignkey')
    op.drop_constraint(None, 'associations', type_='foreignkey')
    op.alter_column("books", "publishedDate", existing_type=sa.DateTime, type_=sa.DATE)
    # ### end Alembic commands ###
