"""empty message

Revision ID: fa3419a9b35f
Revises: fdb44e04b61d
Create Date: 2018-07-09 18:38:56.381266

"""

# revision identifiers, used by Alembic.
revision = 'fa3419a9b35f'
down_revision = 'fdb44e04b61d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associations', sa.Column('checkoutid', sa.Integer(), nullable=False))
    op.drop_column('associations', 'checoutid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associations', sa.Column('checoutid', sa.INTEGER(), nullable=False))
    op.drop_column('associations', 'checkoutid')
    # ### end Alembic commands ###
