"""empty message

Revision ID: fdb44e04b61d
Revises: d1c26047a21c
Create Date: 2018-06-30 13:46:56.746116

"""

# revision identifiers, used by Alembic.
revision = 'fdb44e04b61d'
down_revision = 'd1c26047a21c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('checoutid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('bookid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('checoutid')
    )
    op.add_column('books', sa.Column('publishedDate', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publishedDate')
    op.drop_table('associations')
    # ### end Alembic commands ###
